output   = "infra/rdb/datamodel"
pkgname = "datamodel"
debug = true
wipe     = true
no-tests = true

[psql]
  dbname = "deepscholar"
  host   = "localhost"
  port   = 5452
  user   = "deepscholar_user"
  pass   = "deepscholar2020"
  schema = "public"
  sslmode = "disable"
  blacklist = ["migrations"]
